[window]
opacity = 0.95
blur = true
option_as_alt = "Both"

[font]
# size = 17.0 # Adjust as needed
size = 14.0
normal = {family = "JetBrainsMono Nerd Font"}

[cursor]
style = { shape = "Block", blinking = "Always"}
